const DEFAULT_PRODUCTION_URL="https://routalk-pilot.vercel.app";
function envConfig(){return{token:process.env.VERCEL_TOKEN||"",projectId:process.env.VERCEL_PROJECT_ID||"",teamId:process.env.VERCEL_TEAM_ID||process.env.VERCEL_ORG_ID||"",productionUrl:process.env.PILOT_PRODUCTION_URL||process.env.PRODUCTION_URL||process.env.VERCEL_PROJECT_PRODUCTION_URL||DEFAULT_PRODUCTION_URL}}
function withTeam(path){const{teamId}=envConfig();if(!teamId)return path;const join=path.includes("?")?"&":"?";return`${path}${join}teamId=${encodeURIComponent(teamId)}`}
async function request(path,init={}){const{token}=envConfig();if(!token)return{ok:false,status:null,error:"missing_vercel_token",body:null};try{const r=await fetch(`https://api.vercel.com${withTeam(path)}`,{...init,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json",...(init.headers||{})},cache:"no-store"});const text=await r.text();let body={};try{body=text?JSON.parse(text):{}}catch{body={raw:text}}return{ok:r.ok,status:r.status,error:r.ok?null:(body?.error?.code||body?.error?.message||`vercel_http_${r.status}`),body}}catch(e){return{ok:false,status:null,error:e?.message||"vercel_request_failed",body:null}}}
async function requireRequest(path,init={}){const x=await request(path,init);if(!x.ok){const e=new Error(x.error||"vercel_request_failed");e.status=x.status;throw e}return x.body}
async function inspectProjectAccess(){const c=envConfig();if(!c.projectId)return{ok:false,status:null,error:"missing_vercel_project_id"};if(!c.teamId)return{ok:false,status:null,error:"missing_vercel_team_id"};const x=await request(`/v9/projects/${encodeURIComponent(c.projectId)}`);return{ok:x.ok,status:x.status,error:x.error}}
async function getProject(){const c=envConfig();if(!c.projectId)throw new Error("missing_vercel_project_id");if(!c.teamId)throw new Error("missing_vercel_team_id");return requireRequest(`/v9/projects/${encodeURIComponent(c.projectId)}`)}
async function waitForDeployment(id,timeoutMs=120000){const started=Date.now();while(Date.now()-started<timeoutMs){const d=await requireRequest(`/v13/deployments/${encodeURIComponent(id)}`);const s=d.readyState||d.status;if(s==="READY")return d;if(s==="ERROR"||s==="CANCELED")throw new Error(`deployment_${String(s).toLowerCase()}`);await new Promise(r=>setTimeout(r,2500))}throw new Error("deployment_wait_timeout")}
async function deployProduction(input){const project=await getProject();const repoId=project?.link?.repoId;if(!repoId)throw new Error("vercel_project_missing_github_repo_id");const{projectId}=envConfig();const created=await requireRequest("/v13/deployments",{method:"POST",body:JSON.stringify({name:project.name||"routalk-pilot",project:projectId,target:"production",gitSource:{type:"github",repoId,ref:"main",sha:input.sourceRevision},meta:{pilotLiveProviderProof:input.releaseCandidateId,pilotSourceRevision:input.sourceRevision}})});const deploymentId=created.id||created.uid;if(!deploymentId)throw new Error("vercel_deployment_missing_id");const ready=await waitForDeployment(deploymentId);return{deploymentId,status:"DEPLOYED",evidence:{providerReadyState:ready.readyState||ready.status||null,createdAt:ready.createdAt||null}}}
async function observeProduction({deploymentId,expectedRevision}){const d=await requireRequest(`/v13/deployments/${encodeURIComponent(deploymentId)}`);const observedRevision=d?.meta?.githubCommitSha||d?.gitSource?.sha||d?.meta?.pilotSourceRevision||null;const target=envConfig().productionUrl;const c=new AbortController();const timeout=setTimeout(()=>c.abort(),10000);let status="FAILED",httpStatus=null;try{const r=await fetch(target.replace(/\/+$/,"")+"/",{method:"GET",redirect:"follow",cache:"no-store",signal:c.signal});httpStatus=r.status;const body=await r.text();if(r.ok&&body.includes("<title>Routalk Pilot</title>")&&body.includes("Routalk Pilot"))status="PASSED"}finally{clearTimeout(timeout)}return{observedRevision,expectedRevision,healthChecks:[{id:"canonical-production-root",required:true,status,httpStatus}]}}
function sanitizedStatus(){const c=envConfig();return{provider:"vercel",providerSubsystem:"v1",configured:{token:Boolean(c.token),project:Boolean(c.projectId),team:Boolean(c.teamId),productionUrl:Boolean(c.productionUrl)}}}
module.exports={envConfig,inspectProjectAccess,deployProduction,observeProduction,sanitizedStatus};
