const crypto=require("node:crypto");const{COMMAND_STATES}=require("../lib/command-state");const{createGithubIssueCommandStore}=require("../lib/stores/github-issue-command-store");
const API="https://api.github.com",TIMEOUT=10000;
function eq(a,b){a=Buffer.from(a||"");b=Buffer.from(b||"");return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function sha(v){return/^[a-f0-9]{40}$/i.test(v||"")}
function ghh(t){return{Accept:"application/vnd.github+json",Authorization:`Bearer ${t}`,"User-Agent":"routalk-pilot","X-GitHub-Api-Version":"2022-11-28"}}
async function github(url,token,options={}){const c=new AbortController(),x=setTimeout(()=>c.abort(),TIMEOUT);try{const r=await fetch(url,{...options,headers:{...ghh(token),...(options.headers||{})},signal:c.signal});return{ok:r.ok,status:r.status,data:await r.json().catch(()=>({}))}}catch(e){return{ok:false,status:0,timedOut:e?.name==="AbortError"}}finally{clearTimeout(x)}}
async function observe(base,token,revision){if(!sha(revision))return{checked:false,state:"UNKNOWN",ready:false};const r=await github(`${base}/commits/${revision}/status`,token);if(!r.ok)return{checked:true,state:"UNKNOWN",ready:false,http_status:r.status};const s=(r.data.statuses||[]).find(x=>String(x.context||"").toLowerCase()==="vercel");return{checked:true,state:s?.state||"pending",ready:s?.state==="success",context:s?.context||null,target_url:s?.target_url||null,observed_at:new Date().toISOString()}}
async function verify(req,secret,revision){const host=String(req.headers["x-forwarded-host"]||req.headers.host||"").split(",")[0].trim();if(!host)return{ready:false,state:"INVALID_ORIGIN"};try{const r=await fetch(`https://${host}/api/verify-production?expected_revision=${encodeURIComponent(revision)}`,{headers:{Authorization:`Bearer ${secret}`},cache:"no-store"});const d=await r.json().catch(()=>({}));return{checked:true,ready:r.ok&&d.state==="READY"&&d.revision_match===true,revision_match:d.revision_match===true,expected_revision:d.expected_revision||revision,observed_revision:d.observed_revision||null,state:d.state||"FAILED",http_status:r.status,verified_at:d.verified_at||new Date().toISOString()}}catch{return{checked:true,ready:false,revision_match:false,state:"FAILED"}}}
function state(q,p,d,v){if(q.state==="open")return COMMAND_STATES.QUEUED;if(!p)return COMMAND_STATES.RUNNING;if(p.merged_at)return d?.ready&&v?.ready&&v?.revision_match?COMMAND_STATES.COMPLETED:COMMAND_STATES.MERGED;if(p.state==="open")return COMMAND_STATES.AWAITING_APPROVAL;return COMMAND_STATES.COMPLETED}
module.exports=async(req,res)=>{const id=crypto.randomUUID();res.setHeader("Cache-Control","no-store");res.setHeader("X-Pilot-Request-Id",id);if(req.method!=="GET")return res.status(405).json({error:"Method not allowed",request_id:id});const secret=process.env.PILOT_TRIGGER_SECRET,token=process.env.PILOT_GITHUB_TOKEN;if(!secret||!token)return res.status(503).json({error:"Command lookup is not configured",request_id:id});const a=req.headers.authorization||"",sup=a.startsWith("Bearer ")?a.slice(7):"";if(!eq(sup,secret))return res.status(401).json({error:"Unauthorized",request_id:id});const commandId=String(Array.isArray(req.query.command_id)?req.query.command_id[0]:req.query.command_id||"");if(!/^[A-Za-z0-9][A-Za-z0-9._-]{0,79}$/.test(commandId))return res.status(400).json({error:"Invalid command_id",request_id:id});const owner=process.env.PILOT_GITHUB_OWNER||"pjmcveyroutalk",repo=process.env.PILOT_GITHUB_REPO||"routalk-pilot",base=`${API}/repos/${owner}/${repo}`,store=createGithubIssueCommandStore({baseUrl:base,githubToken:token,githubRequest:github});let q,p;try{[q,p]=await Promise.all([store.findByCommandId(commandId),store.findPullRequestByCommandId(commandId)])}catch(e){return res.status(502).json({error:e.message||"Command lookup failed",request_id:id})}if(!q)return res.status(404).json({error:"Command not found",command_id:commandId,request_id:id});const revision=p?.merge_commit_sha||null;let d=null,v=null;if(p?.merged_at)[d,v]=await Promise.all([observe(base,token,revision),verify(req,secret,revision)]);return res.status(200).json({command_id:commandId,state:state(q,p,d,v),state_source:"pilot_command_model",storage:{adapter:store.name,record:q.number,processed:q.state==="closed",created_at:q.created_at,updated_at:q.updated_at},pull_request:p?{number:p.number,title:p.title,state:p.state,merged:Boolean(p.merged_at),merge_commit_sha:revision,html_url:p.html_url}:null,deployment_observation:d,production_verification:v,request_id:id})};
module.exports._test={state,observe,sha};